;; ClojureScript by Mathieu Legrand <mathieu@legrand.im>
(ns potato.emoji
  (:require [cljsjs.preact :as p]))

(declare unicode-to-aliases)

(defn get-name [alias]
  (condp = (type alias)
    js/String alias
    cljs.core/PersistentVector (first alias)
    ""))

(defn span [item]
  (p/createElement :span nil
                   (p/createElement :span {:class-name "emoji"}
                                    (:text item))
                   (get-name (:id item))))

(def unicode-to-aliases
  {"\uD83D\uDE04"       ["smile" ")" "-)"]
   "\uD83D\uDE03"       "smiley"
   "\uD83D\uDE00"       "grinning"
   "\uD83D\uDE0A"       "blush"
   "\u263A\uFE0F"       "relaxed"
   "\uD83D\uDE09"       "wink"
   "\uD83D\uDE0D"       "heart eyes"
   "\uD83D\uDE18"       "kissing heart"
   "\uD83D\uDE1A"       "kissing closed eyes"
   "\uD83D\uDE17"       "kissing"
   "\uD83D\uDE19"       "kissing smiling eyes"
   "\uD83D\uDE1C"       ["stuck out tongue winking eye" "p" "-p"]
   "\uD83D\uDE1D"       "stuck out tongue closed eyes"
   "\uD83D\uDE1B"       "stuck out tongue"
   "\uD83D\uDE33"       "flushed"
   "\uD83D\uDE01"       "grin"
   "\uD83D\uDE14"       "pensive"
   "\uD83D\uDE0C"       "relieved"
   "\uD83D\uDE12"       "unamused"
   "\uD83D\uDE1E"       ["disappointed" "("]
   "\uD83D\uDE23"       "persevere"
   "\uD83D\uDE22"       "cry"
   "\uD83D\uDE02"       "joy"
   "\uD83D\uDE2D"       "sob"
   "\uD83D\uDE2A"       "sleepy"
   "\uD83D\uDE25"       "disappointed relieved"
   "\uD83D\uDE30"       "cold sweat"
   "\uD83D\uDE05"       "sweat smile"
   "\uD83D\uDE13"       "sweat"
   "\uD83D\uDE29"       "weary"
   "\uD83D\uDE2B"       "tired face"
   "\uD83D\uDE28"       "fearful"
   "\uD83D\uDE31"       "scream"
   "\uD83D\uDE20"       "angry"
   "\uD83D\uDE21"       "rage"
   "\uD83D\uDE24"       "triumph"
   "\uD83D\uDE16"       "confounded"
   "\uD83D\uDE06"       ["laughing" "satisfied"]
   "\uD83D\uDE0B"       "yum"
   "\uD83D\uDE37"       "mask"
   "\uD83D\uDE0E"       ["sunglasses" "cool"]
   "\uD83D\uDE34"       "sleeping"
   "\uD83D\uDE35"       "dizzy face"
   "\uD83D\uDE32"       "astonished"
   "\uD83D\uDE1F"       "worried"
   "\uD83D\uDE26"       "frowning"
   "\uD83D\uDE27"       "anguished"
   "\uD83D\uDE08"       "smiling imp"
   "\uD83D\uDC7F"       "imp"
   "\uD83D\uDE2E"       "open mouth"
   "\uD83D\uDE2C"       "grimacing"
   "\uD83D\uDE10"       "neutral face"
   "\uD83D\uDE15"       ["confused" "/"]
   "\uD83D\uDE2F"       "hushed"
   "\uD83D\uDE36"       "no mouth"
   "\uD83D\uDE07"       "innocent"
   "\uD83D\uDE0F"       "smirk"
   "\uD83D\uDE11"       "expressionless"
   "\uD83D\uDC72"       "man with gua pi mao"
   "\uD83D\uDC73"       "man with turban"
   "\uD83D\uDC6E"       "cop"
   "\uD83D\uDC77"       "construction worker"
   "\uD83D\uDC82"       "guardsman"
   "\uD83D\uDC76"       "baby"
   "\uD83D\uDC66"       "boy"
   "\uD83D\uDC67"       "girl"
   "\uD83D\uDC68"       "man"
   "\uD83D\uDC69"       "woman"
   "\uD83D\uDC74"       "older man"
   "\uD83D\uDC75"       "older woman"
   "\uD83D\uDC71"       "person with blond hair"
   "\uD83D\uDC7C"       "angel"
   "\uD83D\uDC78"       "princess"
   "\uD83D\uDE3A"       "smiley cat"
   "\uD83D\uDE38"       "smile cat"
   "\uD83D\uDE3B"       "heart eyes cat"
   "\uD83D\uDE3D"       "kissing cat"
   "\uD83D\uDE3C"       "smirk cat"
   "\uD83D\uDE40"       "scream cat"
   "\uD83D\uDE3F"       "crying cat face"
   "\uD83D\uDE39"       "joy cat"
   "\uD83D\uDE3E"       "pouting cat"
   "\uD83D\uDC79"       "japanese ogre"
   "\uD83D\uDC7A"       "japanese goblin"
   "\uD83D\uDE48"       "see no evil"
   "\uD83D\uDE49"       "hear no evil"
   "\uD83D\uDE4A"       "speak no evil"
   "\uD83D\uDC80"       "skull"
   "\uD83D\uDC7D"       "alien"
   "\uD83D\uDCA9"       ["hankey" "poop" "shit"]
   "\uD83D\uDD25"       "fire"
   "\u2728"             "sparkles"
   "\uD83C\uDF1F"       "star2"
   "\uD83D\uDCAB"       "dizzy"
   "\uD83D\uDCA5"       ["boom" "collision"]
   "\uD83D\uDCA2"       "anger"
   "\uD83D\uDCA6"       "sweat drops"
   "\uD83D\uDCA7"       "droplet"
   "\uD83D\uDCA4"       "zzz"
   "\uD83D\uDCA8"       "dash"
   "\uD83D\uDC42"       "ear"
   "\uD83D\uDC40"       "eyes"
   "\uD83D\uDC43"       "nose"
   "\uD83D\uDC45"       "tongue"
   "\uD83D\uDC44"       "lips"
   "\uD83D\uDC4D"       ["+1" "thumbsup"]
   "\uD83D\uDC4E"       ["-1" "thumbsdown"]
   "\uD83D\uDC4C"       "ok hand"
   "\uD83D\uDC4A"       ["facepunch" "punch"]
   "\u270A"             "fist"
   "\u270C\uFE0F"       "v"
   "\uD83D\uDC4B"       "wave"
   "\u270B"             ["hand" "raised hand"]
   "\uD83D\uDC50"       "open hands"
   "\uD83D\uDC46"       "point up 2"
   "\uD83D\uDC47"       "point down"
   "\uD83D\uDC49"       "point right"
   "\uD83D\uDC48"       "point left"
   "\uD83D\uDE4C"       "raised hands"
   "\uD83D\uDE4F"       "pray"
   "\u261D\uFE0F"       "point up"
   "\uD83D\uDC4F"       "clap"
   "\uD83D\uDCAA"       "muscle"
   "\uD83D\uDEB6"       "walking"
   "\uD83C\uDFC3"       ["runner" "running"]
   "\uD83D\uDC83"       "dancer"
   "\uD83D\uDC6B"       "couple"
   "\uD83D\uDC6A"       "family"
   "\uD83D\uDC6C"       "two men holding hands"
   "\uD83D\uDC6D"       "two women holding hands"
   "\uD83D\uDC8F"       "couplekiss"
   "\uD83D\uDC91"       "couple with heart"
   "\uD83D\uDC6F"       "dancers"
   "\uD83D\uDE46"       "ok woman"
   "\uD83D\uDE45"       "no good"
   "\uD83D\uDC81"       "information desk person"
   "\uD83D\uDE4B"       "raising hand"
   "\uD83D\uDC86"       "massage"
   "\uD83D\uDC87"       "haircut"
   "\uD83D\uDC85"       "nail care"
   "\uD83D\uDC70"       "bride with veil"
   "\uD83D\uDE4E"       "person with pouting face"
   "\uD83D\uDE4D"       "person frowning"
   "\uD83D\uDE47"       "bow"
   "\uD83C\uDFA9"       "tophat"
   "\uD83D\uDC51"       "crown"
   "\uD83D\uDC52"       "womans hat"
   "\uD83D\uDC5F"       "athletic shoe"
   "\uD83D\uDC5E"       ["man's shoe" "shoe"]
   "\uD83D\uDC61"       "sandal"
   "\uD83D\uDC60"       "high heel"
   "\uD83D\uDC62"       "boot"
   "\uD83D\uDC55"       ["shirt" "t-shirt"]
   "\uD83D\uDC54"       "necktie"
   "\uD83D\uDC5A"       "woman's clothes"
   "\uD83D\uDC57"       "dress"
   "\uD83C\uDFBD"       "running shirt with sash"
   "\uD83D\uDC56"       "jeans"
   "\uD83D\uDC58"       "kimono"
   "\uD83D\uDC59"       "bikini"
   "\uD83D\uDCBC"       "briefcase"
   "\uD83D\uDC5C"       "handbag"
   "\uD83D\uDC5D"       "pouch"
   "\uD83D\uDC5B"       "purse"
   "\uD83D\uDC53"       "eyeglasses"
   "\uD83C\uDF80"       "ribbon"
   "\uD83C\uDF02"       "closed umbrella"
   "\uD83D\uDC84"       "lipstick"
   "\uD83D\uDC9B"       "yellow heart"
   "\uD83D\uDC99"       "blue heart"
   "\uD83D\uDC9C"       "purple heart"
   "\uD83D\uDC9A"       "green heart"
   "\u2764\uFE0F"       "heart"
   "\uD83D\uDC94"       "broken heart"
   "\uD83D\uDC97"       "heartpulse"
   "\uD83D\uDC93"       "heartbeat"
   "\uD83D\uDC95"       "two hearts"
   "\uD83D\uDC96"       "sparkling heart"
   "\uD83D\uDC9E"       "revolving hearts"
   "\uD83D\uDC98"       "cupid"
   "\uD83D\uDC8C"       "love letter"
   "\uD83D\uDC8B"       ["kiss" "*"]
   "\uD83D\uDC8D"       "ring"
   "\uD83D\uDC8E"       "gem"
   "\uD83D\uDC64"       "bust in silhouette"
   "\uD83D\uDC65"       "busts in silhouette"
   "\uD83D\uDCAC"       "speech balloon"
   "\uD83D\uDC63"       "footprints"
   "\uD83D\uDCAD"       "thought balloon"
   "\uD83D\uDC36"       "dog"
   "\uD83D\uDC3A"       "wolf"
   "\uD83D\uDC31"       "cat"
   "\uD83D\uDC2D"       "mouse"
   "\uD83D\uDC39"       "hamster"
   "\uD83D\uDC30"       "rabbit"
   "\uD83D\uDC38"       "frog"
   "\uD83D\uDC2F"       "tiger"
   "\uD83D\uDC28"       "koala"
   "\uD83D\uDC3B"       "bear"
   "\uD83D\uDC37"       "pig"
   "\uD83D\uDC3D"       "pig nose"
   "\uD83D\uDC2E"       "cow"
   "\uD83D\uDC17"       "boar"
   "\uD83D\uDC35"       "monkey face"
   "\uD83D\uDC12"       "monkey"
   "\uD83D\uDC34"       "horse"
   "\uD83D\uDC11"       "sheep"
   "\uD83D\uDC18"       "elephant"
   "\uD83D\uDC3C"       "panda face"
   "\uD83D\uDC27"       "penguin"
   "\uD83D\uDC26"       "bird"
   "\uD83D\uDC24"       "baby chick"
   "\uD83D\uDC25"       "hatched chick"
   "\uD83D\uDC23"       "hatching chick"
   "\uD83D\uDC14"       "chicken"
   "\uD83D\uDC0D"       "snake"
   "\uD83D\uDC22"       "turtle"
   "\uD83D\uDC1B"       "bug"
   "\uD83D\uDC1D"       ["bee" "honeybee"]
   "\uD83D\uDC1C"       "ant"
   "\uD83D\uDC1E"       "beetle"
   "\uD83D\uDC0C"       "snail"
   "\uD83D\uDC19"       "octopus"
   "\uD83D\uDC1A"       "shell"
   "\uD83D\uDC20"       "tropical fish"
   "\uD83D\uDC1F"       "fish"
   "\uD83D\uDC2C"       ["dolphin" "flipper"]
   "\uD83D\uDC33"       "whale"
   "\uD83D\uDC0B"       "whale2"
   "\uD83D\uDC04"       "cow2"
   "\uD83D\uDC0F"       "ram"
   "\uD83D\uDC00"       "rat"
   "\uD83D\uDC03"       "water buffalo"
   "\uD83D\uDC05"       "tiger2"
   "\uD83D\uDC07"       "rabbit2"
   "\uD83D\uDC09"       "dragon"
   "\uD83D\uDC0E"       "racehorse"
   "\uD83D\uDC10"       "goat"
   "\uD83D\uDC13"       "rooster"
   "\uD83D\uDC15"       "dog2"
   "\uD83D\uDC16"       "pig2"
   "\uD83D\uDC01"       "mouse2"
   "\uD83D\uDC02"       "ox"
   "\uD83D\uDC32"       "dragon face"
   "\uD83D\uDC21"       "blowfish"
   "\uD83D\uDC0A"       "crocodile"
   "\uD83D\uDC2B"       "camel"
   "\uD83D\uDC2A"       "dromedary camel"
   "\uD83D\uDC06"       "leopard"
   "\uD83D\uDC08"       "cat2"
   "\uD83D\uDC29"       "poodle"
   "\uD83D\uDC3E"       ["feet" "paw prints"]
   "\uD83D\uDC90"       "bouquet"
   "\uD83C\uDF38"       "cherry blossom"
   "\uD83C\uDF37"       "tulip"
   "\uD83C\uDF40"       "four leaf clover"
   "\uD83C\uDF39"       "rose"
   "\uD83C\uDF3B"       "sunflower"
   "\uD83C\uDF3A"       "hibiscus"
   "\uD83C\uDF41"       "mapleleaf"
   "\uD83C\uDF43"       "leaves"
   "\uD83C\uDF42"       "fallen leaf"
   "\uD83C\uDF3F"       "herb"
   "\uD83C\uDF3E"       "ear of rice"
   "\uD83C\uDF44"       "mushroom"
   "\uD83C\uDF35"       "cactus"
   "\uD83C\uDF34"       "palm tree"
   "\uD83C\uDF32"       "evergreen tree"
   "\uD83C\uDF33"       "deciduous tree"
   "\uD83C\uDF30"       "chestnut"
   "\uD83C\uDF31"       "seedling"
   "\uD83C\uDF3C"       "blossom"
   "\uD83C\uDF10"       "globe with meridians"
   "\uD83C\uDF1E"       "sun with face"
   "\uD83C\uDF1D"       "full moon with face"
   "\uD83C\uDF1A"       "new moon with face"
   "\uD83C\uDF11"       "new moon"
   "\uD83C\uDF12"       "waxing crescent moon"
   "\uD83C\uDF13"       "first quarter moon"
   "\uD83C\uDF14"       ["moon" "waxing gibbous moon"]
   "\uD83C\uDF15"       "full moon"
   "\uD83C\uDF16"       "waning gibbous moon"
   "\uD83C\uDF17"       "last quarter moon"
   "\uD83C\uDF18"       "waning crescent moon"
   "\uD83C\uDF1C"       "last quarter moon with face"
   "\uD83C\uDF1B"       "first quarter moon with face"
   "\uD83C\uDF19"       "crescent moon"
   "\uD83C\uDF0D"       "earth africa"
   "\uD83C\uDF0E"       "earth americas"
   "\uD83C\uDF0F"       "earth asia"
   "\uD83C\uDF0B"       "volcano"
   "\uD83C\uDF0C"       "milky way"
   "\uD83C\uDF20"       "stars"
   "\u2B50"             "star"
   "\u2600\uFE0F"       "sunny"
   "\u26C5"             "partly sunny"
   "\u2601\uFE0F"       "cloud"
   "\u26A1"             "zap"
   "\u2614"             "umbrella"
   "\u2744\uFE0F"       "snowflake"
   "\u26C4"             "snowman"
   "\uD83C\uDF00"       "cyclone"
   "\uD83C\uDF01"       "foggy"
   "\uD83C\uDF08"       "rainbow"
   "\uD83C\uDF0A"       "ocean"
   "\uD83C\uDF8D"       "bamboo"
   "\uD83D\uDC9D"       "gift heart"
   "\uD83C\uDF8E"       "dolls"
   "\uD83C\uDF92"       "school satchel"
   "\uD83C\uDF93"       "mortar board"
   "\uD83C\uDF8F"       "flags"
   "\uD83C\uDF86"       "fireworks"
   "\uD83C\uDF87"       "sparkler"
   "\uD83C\uDF90"       "wind chime"
   "\uD83C\uDF91"       "rice scene"
   "\uD83C\uDF83"       "jack-o-lantern"
   "\uD83D\uDC7B"       "ghost"
   "\uD83C\uDF85"       "santa"
   "\uD83C\uDF84"       "christmas tree"
   "\uD83C\uDF81"       "gift"
   "\uD83C\uDF8B"       "tanabata tree"
   "\uD83C\uDF89"       "tada"
   "\uD83C\uDF8A"       "confetti ball"
   "\uD83C\uDF88"       "balloon"
   "\uD83C\uDF8C"       "crossed flags"
   "\uD83D\uDD2E"       "crystal ball"
   "\uD83C\uDFA5"       "movie camera"
   "\uD83D\uDCF7"       "camera"
   "\uD83D\uDCF9"       "video camera"
   "\uD83D\uDCFC"       "vhs"
   "\uD83D\uDCBF"       "cd"
   "\uD83D\uDCC0"       "dvd"
   "\uD83D\uDCBD"       "minidisc"
   "\uD83D\uDCBE"       "floppy disk"
   "\uD83D\uDCBB"       "computer"
   "\uD83D\uDCF1"       "iphone"
   "\u260E\uFE0F"       ["phone" "telephone"]
   "\uD83D\uDCDE"       "telephone receiver"
   "\uD83D\uDCDF"       "pager"
   "\uD83D\uDCE0"       "fax"
   "\uD83D\uDCE1"       "satellite"
   "\uD83D\uDCFA"       "tv"
   "\uD83D\uDCFB"       "radio"
   "\uD83D\uDD0A"       "loud sound"
   "\uD83D\uDD09"       "sound"
   "\uD83D\uDD08"       "speaker"
   "\uD83D\uDD07"       "mute"
   "\uD83D\uDD14"       "bell"
   "\uD83D\uDD15"       "no bell"
   "\uD83D\uDCE2"       "loudspeaker"
   "\uD83D\uDCE3"       "mega"
   "\u23F3"             "hourglass flowing sand"
   "\u231B"             "hourglass"
   "\u23F0"             "alarm clock"
   "\u231A"             "watch"
   "\uD83D\uDD13"       "unlock"
   "\uD83D\uDD12"       "lock"
   "\uD83D\uDD0F"       "lock with ink pen"
   "\uD83D\uDD10"       "closed lock with key"
   "\uD83D\uDD11"       "key"
   "\uD83D\uDD0E"       "mag right"
   "\uD83D\uDCA1"       "bulb"
   "\uD83D\uDD26"       "flashlight"
   "\uD83D\uDD06"       "high brightness"
   "\uD83D\uDD05"       "low brightness"
   "\uD83D\uDD0C"       "electric plug"
   "\uD83D\uDD0B"       "battery"
   "\uD83D\uDD0D"       "mag"
   "\uD83D\uDEC1"       "bathtub"
   "\uD83D\uDEC0"       "bath"
   "\uD83D\uDEBF"       "shower"
   "\uD83D\uDEBD"       "toilet"
   "\uD83D\uDD27"       "wrench"
   "\uD83D\uDD29"       "nut and bolt"
   "\uD83D\uDD28"       "hammer"
   "\uD83D\uDEAA"       "door"
   "\uD83D\uDEAC"       "smoking"
   "\uD83D\uDCA3"       "bomb"
   "\uD83D\uDD2B"       "gun"
   "\uD83D\uDD2A"       ["hocho" "knife"]
   "\uD83D\uDC8A"       "pill"
   "\uD83D\uDC89"       "syringe"
   "\uD83D\uDCB0"       "moneybag"
   "\uD83D\uDCB4"       "yen"
   "\uD83D\uDCB5"       "dollar"
   "\uD83D\uDCB7"       "pound"
   "\uD83D\uDCB6"       "euro"
   "\uD83D\uDCB3"       "credit card"
   "\uD83D\uDCB8"       "money with wings"
   "\uD83D\uDCF2"       "calling"
   "\uD83D\uDCE7"       "e-mail"
   "\uD83D\uDCE5"       "inbox tray"
   "\uD83D\uDCE4"       "outbox tray"
   "\u2709\uFE0F"       ["email" "envelope"]
   "\uD83D\uDCE9"       "envelope with arrow"
   "\uD83D\uDCE8"       "incoming envelope"
   "\uD83D\uDCEF"       "postal horn"
   "\uD83D\uDCEB"       "mailbox"
   "\uD83D\uDCEA"       "mailbox closed"
   "\uD83D\uDCEC"       "mailbox with mail"
   "\uD83D\uDCED"       "mailbox with no mail"
   "\uD83D\uDCEE"       "postbox"
   "\uD83D\uDCE6"       "package"
   "\uD83D\uDCDD"       ["memo" "pencil"]
   "\uD83D\uDCC4"       "page facing up"
   "\uD83D\uDCC3"       "page with curl"
   "\uD83D\uDCD1"       "bookmark tabs"
   "\uD83D\uDCCA"       "bar chart"
   "\uD83D\uDCC8"       "chart with upwards trend"
   "\uD83D\uDCC9"       "chart with downwards trend"
   "\uD83D\uDCDC"       "scroll"
   "\uD83D\uDCCB"       "clipboard"
   "\uD83D\uDCC5"       "date"
   "\uD83D\uDCC6"       "calendar"
   "\uD83D\uDCC7"       "card index"
   "\uD83D\uDCC1"       "file folder"
   "\uD83D\uDCC2"       "open file folder"
   "\u2702\uFE0F"       "scissors"
   "\uD83D\uDCCC"       "pushpin"
   "\uD83D\uDCCE"       "paperclip"
   "\u2712\uFE0F"       "black nib"
   "\u270F\uFE0F"       "pencil2"
   "\uD83D\uDCCF"       "straight ruler"
   "\uD83D\uDCD0"       "triangular ruler"
   "\uD83D\uDCD5"       "closed book"
   "\uD83D\uDCD7"       "green book"
   "\uD83D\uDCD8"       "blue book"
   "\uD83D\uDCD9"       "orange book"
   "\uD83D\uDCD3"       "notebook"
   "\uD83D\uDCD4"       "notebook with decorative cover"
   "\uD83D\uDCD2"       "ledger"
   "\uD83D\uDCDA"       "books"
   "\uD83D\uDCD6"       ["book" "open book"]
   "\uD83D\uDD16"       "bookmark"
   "\uD83D\uDCDB"       "name badge"
   "\uD83D\uDD2C"       "microscope"
   "\uD83D\uDD2D"       "telescope"
   "\uD83D\uDCF0"       "newspaper"
   "\uD83C\uDFA8"       "art"
   "\uD83C\uDFAC"       "clapper"
   "\uD83C\uDFA4"       "microphone"
   "\uD83C\uDFA7"       "headphones"
   "\uD83C\uDFBC"       "musical score"
   "\uD83C\uDFB5"       "musical note"
   "\uD83C\uDFB6"       "notes"
   "\uD83C\uDFB9"       "musical keyboard"
   "\uD83C\uDFBB"       "violin"
   "\uD83C\uDFBA"       "trumpet"
   "\uD83C\uDFB7"       "saxophone"
   "\uD83C\uDFB8"       "guitar"
   "\uD83D\uDC7E"       "space invader"
   "\uD83C\uDFAE"       "video game"
   "\uD83C\uDCCF"       "black joker"
   "\uD83C\uDFB4"       "flower playing cards"
   "\uD83C\uDC04"       "mahjong"
   "\uD83C\uDFB2"       "game die"
   "\uD83C\uDFAF"       "dart"
   "\uD83C\uDFC8"       "football"
   "\uD83C\uDFC0"       "basketball"
   "\u26BD"             "soccer"
   "\u26BE\uFE0F"       "baseball"
   "\uD83C\uDFBE"       "tennis"
   "\uD83C\uDFB1"       "8ball"
   "\uD83C\uDFC9"       "rugby football"
   "\uD83C\uDFB3"       "bowling"
   "\u26F3"             "golf"
   "\uD83D\uDEB5"       "mountain bicyclist"
   "\uD83D\uDEB4"       "bicyclist"
   "\uD83C\uDFC1"       "checkered flag"
   "\uD83C\uDFC7"       "horse racing"
   "\uD83C\uDFC6"       "trophy"
   "\uD83C\uDFBF"       "ski"
   "\uD83C\uDFC2"       "snowboarder"
   "\uD83C\uDFCA"       "swimmer"
   "\uD83C\uDFC4"       "surfer"
   "\uD83C\uDFA3"       "fishing pole and fish"
   "\u2615"             "coffee"
   "\uD83C\uDF75"       "tea"
   "\uD83C\uDF76"       "sake"
   "\uD83C\uDF7C"       "baby bottle"
   "\uD83C\uDF7A"       "beer"
   "\uD83C\uDF7B"       "beers"
   "\uD83C\uDF78"       "cocktail"
   "\uD83C\uDF79"       "tropical drink"
   "\uD83C\uDF77"       "wine glass"
   "\uD83C\uDF74"       "fork and knife"
   "\uD83C\uDF55"       "pizza"
   "\uD83C\uDF54"       "hamburger"
   "\uD83C\uDF5F"       "fries"
   "\uD83C\uDF57"       "poultry leg"
   "\uD83C\uDF56"       "meat on bone"
   "\uD83C\uDF5D"       "spaghetti"
   "\uD83C\uDF5B"       "curry"
   "\uD83C\uDF64"       "fried shrimp"
   "\uD83C\uDF71"       "bento"
   "\uD83C\uDF63"       "sushi"
   "\uD83C\uDF65"       "fish cake"
   "\uD83C\uDF59"       "rice ball"
   "\uD83C\uDF58"       "rice cracker"
   "\uD83C\uDF5A"       "rice"
   "\uD83C\uDF5C"       "ramen"
   "\uD83C\uDF72"       "stew"
   "\uD83C\uDF62"       "oden"
   "\uD83C\uDF61"       "dango"
   "\uD83C\uDF73"       "egg"
   "\uD83C\uDF5E"       "bread"
   "\uD83C\uDF69"       "doughnut"
   "\uD83C\uDF6E"       "custard"
   "\uD83C\uDF66"       "icecream"
   "\uD83C\uDF68"       "ice cream"
   "\uD83C\uDF67"       "shaved ice"
   "\uD83C\uDF82"       "birthday"
   "\uD83C\uDF70"       "cake"
   "\uD83C\uDF6A"       "cookie"
   "\uD83C\uDF6B"       "chocolate bar"
   "\uD83C\uDF6C"       "candy"
   "\uD83C\uDF6D"       "lollipop"
   "\uD83C\uDF6F"       "honey pot"
   "\uD83C\uDF4E"       "apple"
   "\uD83C\uDF4F"       "green apple"
   "\uD83C\uDF4A"       "tangerine"
   "\uD83C\uDF4B"       "lemon"
   "\uD83C\uDF52"       "cherries"
   "\uD83C\uDF47"       "grapes"
   "\uD83C\uDF49"       "watermelon"
   "\uD83C\uDF53"       "strawberry"
   "\uD83C\uDF51"       "peach"
   "\uD83C\uDF48"       "melon"
   "\uD83C\uDF4C"       "banana"
   "\uD83C\uDF50"       "pear"
   "\uD83C\uDF4D"       "pineapple"
   "\uD83C\uDF60"       "sweet potato"
   "\uD83C\uDF46"       "eggplant"
   "\uD83C\uDF45"       "tomato"
   "\uD83C\uDF3D"       "corn"
   "\uD83C\uDFE0"       "house"
   "\uD83C\uDFE1"       "house with garden"
   "\uD83C\uDFEB"       "school"
   "\uD83C\uDFE2"       "office"
   "\uD83C\uDFE3"       "post office"
   "\uD83C\uDFE5"       "hospital"
   "\uD83C\uDFE6"       "bank"
   "\uD83C\uDFEA"       "convenience store"
   "\uD83C\uDFE9"       "love hotel"
   "\uD83C\uDFE8"       "hotel"
   "\uD83D\uDC92"       "wedding"
   "\u26EA"             "church"
   "\uD83C\uDFEC"       "department store"
   "\uD83C\uDFE4"       "european post office"
   "\uD83C\uDF07"       "city sunrise"
   "\uD83C\uDF06"       "city sunset"
   "\uD83C\uDFEF"       "japanese castle"
   "\uD83C\uDFF0"       "european castle"
   "\u26FA"             "tent"
   "\uD83C\uDFED"       "factory"
   "\uD83D\uDDFC"       "tokyo tower"
   "\uD83D\uDDFE"       "japan"
   "\uD83D\uDDFB"       "mount fuji"
   "\uD83C\uDF04"       "sunrise over mountains"
   "\uD83C\uDF05"       "sunrise"
   "\uD83C\uDF03"       "night with stars"
   "\uD83D\uDDFD"       "statue of liberty"
   "\uD83C\uDF09"       "bridge at night"
   "\uD83C\uDFA0"       "carousel horse"
   "\uD83C\uDFA1"       "ferris wheel"
   "\u26F2"             "fountain"
   "\uD83C\uDFA2"       "roller coaster"
   "\uD83D\uDEA2"       "ship"
   "\u26F5"             ["boat" "sailboat"]
   "\uD83D\uDEA4"       "speedboat"
   "\uD83D\uDEA3"       "rowboat"
   "\u2693"             "anchor"
   "\uD83D\uDE80"       "rocket"
   "\u2708\uFE0F"       "airplane"
   "\uD83D\uDCBA"       "seat"
   "\uD83D\uDE81"       "helicopter"
   "\uD83D\uDE82"       "steam locomotive"
   "\uD83D\uDE8A"       "tram"
   "\uD83D\uDE89"       "station"
   "\uD83D\uDE9E"       "mountain railway"
   "\uD83D\uDE86"       "train2"
   "\uD83D\uDE84"       "bullettrain side"
   "\uD83D\uDE85"       "bullettrain front"
   "\uD83D\uDE88"       "light rail"
   "\uD83D\uDE87"       "metro"
   "\uD83D\uDE9D"       "monorail"
   "\uD83D\uDE8B"       "train"
   "\uD83D\uDE83"       "railway car"
   "\uD83D\uDE8E"       "trolleybus"
   "\uD83D\uDE8C"       "bus"
   "\uD83D\uDE8D"       "oncoming bus"
   "\uD83D\uDE99"       "blue car"
   "\uD83D\uDE98"       "oncoming automobile"
   "\uD83D\uDE97"       ["car" "red car"]
   "\uD83D\uDE95"       "taxi"
   "\uD83D\uDE96"       "oncoming taxi"
   "\uD83D\uDE9B"       "articulated lorry"
   "\uD83D\uDE9A"       "truck"
   "\uD83D\uDEA8"       "rotating light"
   "\uD83D\uDE93"       "police car"
   "\uD83D\uDE94"       "oncoming police car"
   "\uD83D\uDE92"       "fire engine"
   "\uD83D\uDE91"       "ambulance"
   "\uD83D\uDE90"       "minibus"
   "\uD83D\uDEB2"       "bike"
   "\uD83D\uDEA1"       "aerial tramway"
   "\uD83D\uDE9F"       "suspension railway"
   "\uD83D\uDEA0"       "mountain cableway"
   "\uD83D\uDE9C"       "tractor"
   "\uD83D\uDC88"       "barber"
   "\uD83D\uDE8F"       "busstop"
   "\uD83C\uDFAB"       "ticket"
   "\uD83D\uDEA6"       "vertical traffic light"
   "\uD83D\uDEA5"       "traffic light"
   "\u26A0\uFE0F"       "warning"
   "\uD83D\uDEA7"       "construction"
   "\uD83D\uDD30"       "beginner"
   "\u26FD"             "fuelpump"
   "\uD83C\uDFEE"       ["izakaya lantern" "lantern"]
   "\uD83C\uDFB0"       "slot machine"
   "\u2668\uFE0F"       "hotsprings"
   "\uD83D\uDDFF"       "moyai"
   "\uD83C\uDFAA"       "circus tent"
   "\uD83C\uDFAD"       "performing arts"
   "\uD83D\uDCCD"       "round pushpin"
   "\uD83D\uDEA9"       "triangular flag on post"
   "\uD83C\uDDEF\uD83C\uDDF5" "jp"
   "\uD83C\uDDF0\uD83C\uDDF7" "kr"
   "\uD83C\uDDE9\uD83C\uDDEA" "de"
   "\uD83C\uDDE8\uD83C\uDDF3" "cn"
   "\uD83C\uDDFA\uD83C\uDDF8" "us"
   "\uD83C\uDDEB\uD83C\uDDF7" "fr"
   "\uD83C\uDDEA\uD83C\uDDF8" "es"
   "\uD83C\uDDEE\uD83C\uDDF9" "it"
   "\uD83C\uDDF7\uD83C\uDDFA" "ru"
   "\uD83C\uDDEC\uD83C\uDDE7" ["gb" "uk"]
   "1\uFE0F\u20E3"      "one"
   "2\uFE0F\u20E3"      "two"
   "3\uFE0F\u20E3"      "three"
   "4\uFE0F\u20E3"      "four"
   "5\uFE0F\u20E3"      "five"
   "6\uFE0F\u20E3"      "six"
   "7\uFE0F\u20E3"      "seven"
   "8\uFE0F\u20E3"      "eight"
   "9\uFE0F\u20E3"      "nine"
   "0\uFE0F\u20E3"      "zero"
   "\uD83D\uDD1F"       "keycap ten"
   "\uD83D\uDD22"       "1234"
   "#\uFE0F\u20E3"      "hash"
   "\uD83D\uDD23"       "symbols"
   "\u2B06\uFE0F"       "arrow up"
   "\u2B07\uFE0F"       "arrow down"
   "\u2B05\uFE0F"       "arrow left"
   "\u27A1\uFE0F"       "arrow right"
   "\uD83D\uDD20"       "capital abcd"
   "\uD83D\uDD21"       "abcd"
   "\uD83D\uDD24"       "abc"
   "\u2197\uFE0F"       "arrow upper right"
   "\u2196\uFE0F"       "arrow upper left"
   "\u2198\uFE0F"       "arrow lower right"
   "\u2199\uFE0F"       "arrow lower left"
   "\u2194\uFE0F"       "left right arrow"
   "\u2195\uFE0F"       "arrow up down"
   "\uD83D\uDD04"       "arrows counterclockwise"
   "\u25C0\uFE0F"       "arrow backward"
   "\u25B6\uFE0F"       "arrow forward"
   "\uD83D\uDD3C"       "arrow up small"
   "\uD83D\uDD3D"       "arrow down small"
   "\u21A9\uFE0F"       "leftwards arrow with hook"
   "\u21AA\uFE0F"       "arrow right hook"
   "\u2139\uFE0F"       "information source"
   "\u23EA"             "rewind"
   "\u23E9"             "fast forward"
   "\u23EB"             "arrow double up"
   "\u23EC"             "arrow double down"
   "\u2935\uFE0F"       "arrow heading down"
   "\u2934\uFE0F"       "arrow heading up"
   "\uD83C\uDD97"       "ok"
   "\uD83D\uDD00"       "twisted rightwards arrows"
   "\uD83D\uDD01"       "repeat"
   "\uD83D\uDD02"       "repeat one"
   "\uD83C\uDD95"       "new"
   "\uD83C\uDD99"       "up"
   "\uD83C\uDD92"       "cool"
   "\uD83C\uDD93"       "free"
   "\uD83C\uDD96"       "ng"
   "\uD83D\uDCF6"       "signal strength"
   "\uD83C\uDFA6"       "cinema"
   "\uD83C\uDE01"       "koko"
   "\uD83C\uDE2F"       ["u6307" "finger"]
   "\uD83C\uDE33"       ["u7a7a" "empty"]
   "\uD83C\uDE35"       "u6e80"
   "\uD83C\uDE34"       ["u5408" "close"]
   "\uD83C\uDE32"       ["u7981" "ban"]
   "\uD83C\uDE50"       "ideograph advantage"
   "\uD83C\uDE39"       ["u5272" "assignment"]
   "\uD83C\uDE3A"       "u55b6"
   "\uD83C\uDE36"       ["u6709" "have"]
   "\uD83C\uDE1A"       ["u7121" "no"]
   "\uD83D\uDEBB"       "restroom"
   "\uD83D\uDEB9"       "mens"
   "\uD83D\uDEBA"       "womens"
   "\uD83D\uDEBC"       "baby symbol"
   "\uD83D\uDEBE"       "wc"
   "\uD83D\uDEB0"       "potable water"
   "\uD83D\uDEAE"       "put litter in its place"
   "\uD83C\uDD7F\uFE0F" "parking"
   "\u267F"             "wheelchair"
   "\uD83D\uDEAD"       "no smoking"
   "\uD83C\uDE37\uFE0F" "u6708"
   "\uD83C\uDE38"       "u7533"
   "\uD83C\uDE02\uFE0F" "sa"
   "\u24C2\uFE0F"       "m"
   "\uD83D\uDEC2"       "passport control"
   "\uD83D\uDEC4"       "baggage claim"
   "\uD83D\uDEC5"       "left luggage"
   "\uD83D\uDEC3"       "customs"
   "\uD83C\uDE51"       "accept"
   "\u3299\uFE0F"       "secret"
   "\u3297\uFE0F"       "congratulations"
   "\uD83C\uDD91"       "cl"
   "\uD83C\uDD98"       "sos"
   "\uD83C\uDD94"       "id"
   "\uD83D\uDEAB"       "no entry sign"
   "\uD83D\uDD1E"       "underage"
   "\uD83D\uDCF5"       "no mobile phones"
   "\uD83D\uDEAF"       "do not litter"
   "\uD83D\uDEB1"       "non-potable water"
   "\uD83D\uDEB3"       "no bicycles"
   "\uD83D\uDEB7"       "no pedestrians"
   "\uD83D\uDEB8"       "children crossing"
   "\u26D4"             "no entry"
   "\u2733\uFE0F"       "eight spoked asterisk"
   "\u2747\uFE0F"       "sparkle"
   "\u274E"             "negative squared cross mark"
   "\u2705"             "white check mark"
   "\u2734\uFE0F"       "eight pointed black star"
   "\uD83D\uDC9F"       "heart decoration"
   "\uD83C\uDD9A"       "vs"
   "\uD83D\uDCF3"       "vibration mode"
   "\uD83D\uDCF4"       "mobile phone off"
   "\uD83C\uDD70\uFE0F" "a"
   "\uD83C\uDD71\uFE0F" "b"
   "\uD83C\uDD8E"       "ab"
   "\uD83C\uDD7E\uFE0F" "o2"
   "\uD83D\uDCA0"       "diamond shape with a dot inside"
   "\u27BF"             "loop"
   "\u267B\uFE0F"       "recycle"
   "\u2648"             "aries"
   "\u2649"             "taurus"
   "\u264A"             "gemini"
   "\u264B"             "cancer"
   "\u264C"             "leo"
   "\u264D"             "virgo"
   "\u264E"             "libra"
   "\u264F"             "scorpius"
   "\u2650"             "sagittarius"
   "\u2651"             "capricorn"
   "\u2652"             "aquarius"
   "\u2653"             "pisces"
   "\u26CE"             "ophiuchus"
   "\uD83D\uDD2F"       "six pointed star"
   "\uD83C\uDFE7"       "atm"
   "\uD83D\uDCB9"       "chart"
   "\uD83D\uDCB2"       "heavy dollar sign"
   "\uD83D\uDCB1"       "currency exchange"
   "\u00A9\uFE0F"       "copyright"
   "\u00AE\uFE0F"       "registered"
   "\u2122\uFE0F"       "tm"
   "\u274C"             "x"
   "\u203C\uFE0F"       "bangbang"
   "\u2049\uFE0F"       "interrobang"
   "\u2757"             ["exclamation" "heavy exclamation mark"]
   "\u2753"             "question"
   "\u2755"             "grey exclamation"
   "\u2754"             "grey question"
   "\u2B55"             "o"
   "\uD83D\uDD1D"       "top"
   "\uD83D\uDD1A"       "end"
   "\uD83D\uDD19"       "back"
   "\uD83D\uDD1B"       "on"
   "\uD83D\uDD1C"       "soon"
   "\uD83D\uDD03"       "arrows clockwise"
   "\uD83D\uDD5B"       "clock 12"
   "\uD83D\uDD67"       "clock 12:30"
   "\uD83D\uDD50"       "clock 1"
   "\uD83D\uDD5C"       "clock 1:30"
   "\uD83D\uDD51"       "clock 2"
   "\uD83D\uDD5D"       "clock 2:30"
   "\uD83D\uDD52"       "clock 3"
   "\uD83D\uDD5E"       "clock 3:30"
   "\uD83D\uDD53"       "clock 4"
   "\uD83D\uDD5F"       "clock 4:30"
   "\uD83D\uDD54"       "clock 5"
   "\uD83D\uDD60"       "clock 5:30"
   "\uD83D\uDD55"       "clock 6"
   "\uD83D\uDD56"       "clock 7"
   "\uD83D\uDD57"       "clock 8"
   "\uD83D\uDD58"       "clock 9"
   "\uD83D\uDD59"       "clock 10"
   "\uD83D\uDD5A"       "clock 11"
   "\uD83D\uDD61"       "clock 6:30"
   "\uD83D\uDD62"       "clock 7:30"
   "\uD83D\uDD63"       "clock 8:30"
   "\uD83D\uDD64"       "clock 9:30"
   "\uD83D\uDD65"       "clock 10:30"
   "\uD83D\uDD66"       "clock 11:30"
   "\u2716\uFE0F"       "heavy multiplication x"
   "\u2795"             "heavy plus sign"
   "\u2796"             "heavy minus sign"
   "\u2797"             "heavy division sign"
   "\u2660\uFE0F"       "spades"
   "\u2665\uFE0F"       "hearts"
   "\u2663\uFE0F"       "clubs"
   "\u2666\uFE0F"       "diamonds"
   "\uD83D\uDCAE"       "white flower"
   "\uD83D\uDCAF"       "100"
   "\u2714\uFE0F"       "heavy check mark"
   "\u2611\uFE0F"       "ballot box with check"
   "\uD83D\uDD18"       "radio button"
   "\uD83D\uDD17"       "link"
   "\u27B0"             "curly loop"
   "\u3030\uFE0F"       "wavy dash"
   "\u303D\uFE0F"       "part alternation mark"
   "\uD83D\uDD31"       "trident"
   "\u25FC\uFE0F"       "black medium square"
   "\u25FB\uFE0F"       "white medium square"
   "\u25FE"             "black medium small square"
   "\u25FD"             "white medium small square"
   "\u25AA\uFE0F"       "black small square"
   "\u25AB\uFE0F"       "white small square"
   "\uD83D\uDD3A"       "small red triangle"
   "\uD83D\uDD32"       "black square button"
   "\uD83D\uDD33"       "white square button"
   "\u26AB"             "black circle"
   "\u26AA"             "white circle"
   "\uD83D\uDD34"       "red circle"
   "\uD83D\uDD35"       "large blue circle"
   "\uD83D\uDD3B"       "small red triangle down"
   "\u2B1C"             "white large square"
   "\u2B1B"             "black large square"
   "\uD83D\uDD36"       "large orange diamond"
   "\uD83D\uDD37"       "large blue diamond"
   "\uD83D\uDD38"       "small orange diamond"
   "\uD83D\uDD39"       "small blue diamond"})

