(ns potato.urls)

(def settings               "/settings")
(def send-chat              "/send_chat")
(def history                "/history")
(def domain                 "/")
(def chat-updates           "/chat_updates3")
(def chat-updates4          "/chat_updates4")
(def user-image             "/user_image")
(def delete-chat            "/delete_chat")
(def load-chat              "/load_chat")
(def load-channels-for-user "/load_channels_for_user")
(def load-channel           "/load_channel")
(def members                "/members")
(def update-chat            "/update_chat")
(def start-private-chat     "/start_private_chat")
(def type-notification      "/type_notification")
(def remove-channel         "/remove_channel")
(def update-channel         "/update_channel")
(def update-star            "/update_star")
(def update-hidden          "/update_hidden")

(defonce channel-root       (aget js/window "channelUrl"))
