# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
POTATO_LOCAL_DIR        = `git rev-parse --show-toplevel`.chomp
POTATO_SERVER_DIR       = "/potato"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box    = "freebsd/FreeBSD-11.0-CURRENT"
  config.ssh.shell = "sh"
  #config.vm.box_check_update = false

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder POTATO_LOCAL_DIR, POTATO_SERVER_DIR, mount_options: ["noatime,ro"], nfs: true

  config.vm.provider "vmware_fusion" do |v|
    v.vmx["memsize"]  = "2048"
    v.vmx["numvcpus"] = "4"
  end

  config.vm.provider "virtualbox" do |vb, override|
    vb.gui    = false
    vb.memory = 2048
    vb.cpus   = 4
    vb.name   = "Potato virtualbox"
    vb.customize ["modifyvm", :id, "--audio", "none"]
  end

  config.vm.provision "file",  source: "provision.cl", destination: "/var/tmp/provision.cl"
  config.vm.provision "shell", path:   "provision.sh"
end
