# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos71"
  config.vm.box_check_update = false
  config.vm.define "potato-vagrant-dev" do |potato_vagrant_dev|
  end

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "..", "/potato", mount_options: [ "dmode=775,fmode=775"], mount_options: ["uid=1214,gid=100"]
  config.vm.synced_folder "..", "/potato/shared", mount_options: [ "dmode=775,fmode=775"], mount_options: ["uid=1214,gid=100"]

  if ENV['http_proxy'] != nil then
    puts "-- Using proxy #{ENV['http_proxy']}, make sure the plugin vagrant-proxyconf is installed"
    config.proxy.http     = ENV['http_proxy']
    config.proxy.https    = ENV['http_proxy']
    config.proxy.no_proxy = "localhost,127.0.0.1"
  end

  config.vm.provision "ansible", run: "always" do |ansible|
    ansible.playbook      = `git rev-parse --show-toplevel`.chomp + "/deploy/development.yml"
    # ansible.verbose = "vvv" # Uncomment to enable ansible verbose
    String branch = "master"
    if ENV['POTATO_DEPLOY_BRANCH'] then
      branch = ENV['POTATO_DEPLOY_BRANCH']
    end
    ansible.extra_vars    = {
        local_user: "#{ENV['USER']}",
        project_local_path: "#{Dir.pwd}/..",
        deployment_branch: branch
    }
  end

  config.vm.provider "vmware_fusion" do |v|
    v.vmx["memsize"] = "2048"
    v.vmx["numvcpus"] = "4"
  end
end
